// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8W-tAN_WLOset7jOzCtZIoFsUFyvHl4o',
    appId: '1:157725588873:web:ff80ba2242b279118ff558',
    messagingSenderId: '157725588873',
    projectId: 'instagram-8a227',
    authDomain: 'instagram-8a227.firebaseapp.com',
    storageBucket: 'instagram-8a227.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgjPqpMHJmAzWTSVumlbaNb5d_3eIE1IQ',
    appId: '1:157725588873:android:d9398f97cf47f7ea8ff558',
    messagingSenderId: '157725588873',
    projectId: 'instagram-8a227',
    storageBucket: 'instagram-8a227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9M51EZemHD1jH-B4nZq-QP0piFHDfUjE',
    appId: '1:157725588873:ios:5d331b2c0d149ed48ff558',
    messagingSenderId: '157725588873',
    projectId: 'instagram-8a227',
    storageBucket: 'instagram-8a227.appspot.com',
    iosClientId: '157725588873-fvt73snp37feh5vv3nmeb0vqe2f9ffrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9M51EZemHD1jH-B4nZq-QP0piFHDfUjE',
    appId: '1:157725588873:ios:43f1b42b0562d2978ff558',
    messagingSenderId: '157725588873',
    projectId: 'instagram-8a227',
    storageBucket: 'instagram-8a227.appspot.com',
    iosClientId: '157725588873-sk8d1bdie4evggqalg0kphblc59k0c3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest1.RunnerTests',
  );
}
